/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorJuego;

/**
 *
 * @author usuario
 */
public class PanelInformacion extends javax.swing.JPanel {
    ControladorJuego controlador;
    
    /**
     * Creates new form PanelInformacion
     */
    public PanelInformacion(ControladorJuego cj) {
        initComponents();
        controlador = cj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        TxtApuestaTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtMontoApuesta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFichasDisponibles = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtNombreJugador = new javax.swing.JTextField();
        txtNombreRival = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Total Apostado");
        add(jLabel5);
        jLabel5.setBounds(430, 20, 121, 22);

        TxtApuestaTotal.setEditable(false);
        TxtApuestaTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(TxtApuestaTotal);
        TxtApuestaTotal.setBounds(560, 20, 120, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Su Saldo");
        add(jLabel4);
        jLabel4.setBounds(700, 20, 80, 22);

        txtSaldo.setEditable(false);
        txtSaldo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(txtSaldo);
        txtSaldo.setBounds(790, 20, 120, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Monto Apuesta");
        add(jLabel3);
        jLabel3.setBounds(430, 70, 120, 22);

        TxtMontoApuesta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(TxtMontoApuesta);
        TxtMontoApuesta.setBounds(560, 70, 120, 28);

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Apostar");
        add(jButton2);
        jButton2.setBounds(700, 70, 120, 31);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Fichas Disponibles");
        add(jLabel2);
        jLabel2.setBounds(10, 150, 151, 22);

        txtFichasDisponibles.setEditable(false);
        txtFichasDisponibles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(txtFichasDisponibles);
        txtFichasDisponibles.setBounds(180, 150, 70, 28);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Robar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(270, 150, 81, 31);

        txtNombreJugador.setEditable(false);
        txtNombreJugador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNombreJugador.setText("Nombre Completo Jugador");
        add(txtNombreJugador);
        txtNombreJugador.setBounds(90, 20, 320, 28);

        txtNombreRival.setEditable(false);
        txtNombreRival.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNombreRival.setText("Nombre Completo Jugador Rival");
        add(txtNombreRival);
        txtNombreRival.setBounds(90, 70, 320, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Jugador:");
        add(jLabel6);
        jLabel6.setBounds(10, 20, 80, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Rival:");
        add(jLabel7);
        jLabel7.setBounds(30, 70, 50, 22);

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setText("Descartar Ficha");
        add(jButton3);
        jButton3.setBounds(560, 150, 340, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("Robaría una Ficha.");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtApuestaTotal;
    private javax.swing.JTextField TxtMontoApuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtFichasDisponibles;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtNombreRival;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
