/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorReplay;
import logica.Movimiento;

/**
 *
 * @author usuario
 */
public class PanelInformacionReplay extends javax.swing.JPanel {
    private ControladorReplay controlador;
    /**
     * Creates new form PanelInformacionReplay
     * @param controlador
     */
    public PanelInformacionReplay(ControladorReplay controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJugador = new javax.swing.JTextField();
        txtTotalApostado = new javax.swing.JTextField();
        txtFechaHora = new javax.swing.JTextField();
        btnMovimientoAnterior = new javax.swing.JButton();
        btnMovimientoSiguiente = new javax.swing.JButton();
        txtGanador = new javax.swing.JTextField();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Jugador:");
        add(jLabel1);
        jLabel1.setBounds(50, 60, 70, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Apostado");
        add(jLabel2);
        jLabel2.setBounds(910, 70, 150, 22);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Fecha y Hora:");
        add(jLabel3);
        jLabel3.setBounds(10, 100, 120, 22);

        txtJugador.setEditable(false);
        txtJugador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(txtJugador);
        txtJugador.setBounds(130, 60, 360, 28);

        txtTotalApostado.setEditable(false);
        txtTotalApostado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTotalApostado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalApostadoActionPerformed(evt);
            }
        });
        add(txtTotalApostado);
        txtTotalApostado.setBounds(910, 100, 150, 28);

        txtFechaHora.setEditable(false);
        txtFechaHora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(txtFechaHora);
        txtFechaHora.setBounds(130, 100, 360, 28);

        btnMovimientoAnterior.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnMovimientoAnterior.setText("<<< Jugada Anterior");
        btnMovimientoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoAnteriorActionPerformed(evt);
            }
        });
        add(btnMovimientoAnterior);
        btnMovimientoAnterior.setBounds(10, 10, 220, 31);

        btnMovimientoSiguiente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnMovimientoSiguiente.setText("Siguiente Jugada >>>");
        btnMovimientoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientoSiguienteActionPerformed(evt);
            }
        });
        add(btnMovimientoSiguiente);
        btnMovimientoSiguiente.setBounds(840, 10, 220, 30);

        txtGanador.setEditable(false);
        txtGanador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtGanador.setForeground(new java.awt.Color(255, 51, 51));
        txtGanador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGanador.setText(" ");
        add(txtGanador);
        txtGanador.setBounds(240, 10, 590, 28);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalApostadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalApostadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalApostadoActionPerformed

    private void btnMovimientoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoSiguienteActionPerformed
        // TODO add your handling code here:
        controlador.movimientoSiguiente();
    }//GEN-LAST:event_btnMovimientoSiguienteActionPerformed

    private void btnMovimientoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientoAnteriorActionPerformed
        // TODO add your handling code here:
        controlador.movimientoAnterior();
    }//GEN-LAST:event_btnMovimientoAnteriorActionPerformed

    void mostrar(Movimiento movimiento) {
        if(movimiento.getGanador() != null){
            txtGanador.setText("El ganador es: " + movimiento.getGanador().getNombreCompleto());
        }
        else
            txtGanador.setText("");
        
        if(movimiento.getTablero().isEmpty()){
            txtFechaHora.setText("Aún no se ha jugado");
            txtJugador.setText("Aún no se ha jugado");
        }
        else{
            txtFechaHora.setText(movimiento.getFechaHora().toString());
            txtJugador.setText(movimiento.getJugador().getNombreCompleto());
        }
        txtTotalApostado.setText(movimiento.getPozoApuestas()+"");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovimientoAnterior;
    private javax.swing.JButton btnMovimientoSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFechaHora;
    private javax.swing.JTextField txtGanador;
    private javax.swing.JTextField txtJugador;
    private javax.swing.JTextField txtTotalApostado;
    // End of variables declaration//GEN-END:variables
}
