/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorPartidas;
import controladores.VistaPartidas;
import java.util.ArrayList;
import logica.Jugador;
import logica.Partida;

/**
 *
 * @author usuario
 */
public class Partidas extends javax.swing.JFrame implements VistaPartidas{
    
    private ControladorPartidas controlador;
    /**
     * Creates new form Partidas
     */
    public Partidas() {
        initComponents();
        controlador = new ControladorPartidas(this);
        setTitle("Listado de Partidas");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPartidas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnVerPartida = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lstPartidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPartidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstPartidas);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Listado de Partidas");

        btnVerPartida.setBackground(new java.awt.Color(153, 255, 153));
        btnVerPartida.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVerPartida.setText("Ver Partida");
        btnVerPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPartidaActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrarSesion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerPartida)
                    .addComponent(btnCerrarSesion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 542, 312);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controlador.salir();
    }//GEN-LAST:event_formWindowClosing

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        controlador.salir();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVerPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPartidaActionPerformed
        abrirPartida();
    }//GEN-LAST:event_btnVerPartidaActionPerformed
    
    private void lstPartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPartidasMouseClicked
        if(evt.getClickCount() >= 2)
            abrirPartida();
    }//GEN-LAST:event_lstPartidasMouseClicked
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnVerPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstPartidas;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void cerrar() {
        dispose();
    }
    
    @Override
    public void mostrarPartidas(ArrayList<Partida> partidas) {
        ArrayList<String> lista = new ArrayList();
        
        for(Partida p:partidas){
            String linea = "[En juego] ";;
            String g = "Aún no hay ganador";
            
            Jugador ganador = p.getGanador();
            
            if(ganador != null){
                linea = "[Finalizada] ";
                g = ganador.getNombreCompleto();
            }
            
            linea += p.getJugadores().get(0).getNombreCompleto() + " ($ " + p.getJugadores().get(0).getSaldo() + ") - ";
            linea += p.getJugadores().get(1).getNombreCompleto() + " ($ " + p.getJugadores().get(1).getSaldo() + ") : $";
            
            linea += p.getPozoApuestas()+" => ";
            
            linea += g;
            
            lista.add(linea);
        }
        
        lstPartidas.setListData(lista.toArray());
        this.validate();
    }

    @Override
    public void mostrarPartida(Partida partida) {
        new Replay(this, false, partida).setVisible(true);
    }

    private void abrirPartida() {
        int nroPartidaSeleccionada = lstPartidas.getSelectedIndex();
        controlador.abrirPartida(nroPartidaSeleccionada);
    }
}
