/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Sistema;
import logica.Usuario;

/**
 *
 * @author usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private ArrayList<javax.swing.JFrame> ventanas = new ArrayList(); //Ver si se podría resolver haciendolo observable y a todas las demás ventanas hacerlas Observadoras de esta
    private Sistema sistema = Sistema.getInstancia();
    /**
     * Creates new form Login
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ddlRol = new javax.swing.JComboBox();
        txtPassword = new javax.swing.JPasswordField();
        bntApagarServidor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUsuario.setToolTipText("Usuario");

        btnLogin.setBackground(new java.awt.Color(153, 255, 153));
        btnLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLogin.setText("Generar Interfaz");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Password:");

        ddlRol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ddlRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Rol", "Administrador", "Jugador" }));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        bntApagarServidor.setBackground(new java.awt.Color(255, 153, 153));
        bntApagarServidor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bntApagarServidor.setText("Apagar Servidor");
        bntApagarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntApagarServidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPassword)))
                    .addComponent(ddlRol, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntApagarServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ddlRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(bntApagarServidor)
                .addContainerGap())
        );

        setBounds(0, 0, 270, 313);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void bntApagarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntApagarServidorActionPerformed
        // TODO add your handling code here:
        apagarServidor();
    }//GEN-LAST:event_bntApagarServidorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        apagarServidor();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntApagarServidor;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox ddlRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void login() {
        String usu = txtUsuario.getText();
        String pass = txtPassword.getText();

//HAY QUE VER EL TEMA LOGIN!!! Ahora, no importa si es jugador o administrador, entra con la opción que haya seleccionado el usuario
        if(ddlRol.getSelectedIndex() != 0){
            Usuario u = Sistema.getInstancia().login(usu, pass);
            if(u != null){
                javax.swing.JFrame v;
                
                if(ddlRol.getSelectedIndex() == 1){
                    v = new Partidas(u);
                }
                else{
                    v = new Juego(u);
                }
                
                ventanas.add(v);
                v.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Error, intente nuevamente."); //Ver si resolvemos con una excepcion o dejamos así
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol."); //Ver si resolvemos con una excepcion o dejamos así
        }
    }

    private void apagarServidor() {
        if(sistema.partidasFinalizadas()){
            for(javax.swing.JFrame v:ventanas){ //Ver si se podría resolver haciendolo observable y a todas las demás ventanas hacerlas Observadoras de esta
                v.dispose();
            }
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this, "Para cerrar el servidor deben estar todas las partidas finalizadas.");
    }
}
