/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import logica.Partida;

/**
 *
 * @author usuario
 */
public class Replay extends javax.swing.JDialog {
    private Partida partida;
    /**
     * Creates new form Replay
     */
    public Replay(java.awt.Frame parent, boolean modal, Partida p) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        partida = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugadaSiguiente = new javax.swing.JButton();
        btnJugadaAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnJugadaSiguiente.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnJugadaSiguiente.setText(">>>");
        btnJugadaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadaSiguienteActionPerformed(evt);
            }
        });

        btnJugadaAnterior.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnJugadaAnterior.setText("<<<");
        btnJugadaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadaAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJugadaAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                .addComponent(btnJugadaSiguiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugadaSiguiente)
                    .addComponent(btnJugadaAnterior))
                .addContainerGap())
        );

        setBounds(0, 0, 652, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugadaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadaSiguienteActionPerformed
        // TODO add your handling code here:
        System.out.println("Se mostraría el siguiente movimiento.");
    }//GEN-LAST:event_btnJugadaSiguienteActionPerformed

    private void btnJugadaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadaAnteriorActionPerformed
        // TODO add your handling code here:
        System.out.println("Se mostratía el anterior movimiento.");
    }//GEN-LAST:event_btnJugadaAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugadaAnterior;
    private javax.swing.JButton btnJugadaSiguiente;
    // End of variables declaration//GEN-END:variables
}
