/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controladores.ControladorLogin;
import controladores.VistaLogin;
import javax.swing.JOptionPane;
import logica.Administrador;
import logica.Jugador;
import utilidades.ObligatorioException;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JDialog implements VistaLogin{

    private ControladorLogin controlador;
    
    public Login(java.awt.Frame parent, boolean modal, boolean jugador) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorLogin(this,jugador);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(70, 50, 180, 30);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(100, 170, 110, 30);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 180, 30);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 180, 30);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass);
        txtPass.setBounds(70, 120, 180, 30);

        setBounds(0, 0, 343, 275);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        login();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        login();
    }//GEN-LAST:event_txtPassActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    

    private void login() {
        controlador.login(txtNombre.getText(),txtPass.getText());       
    }

    @Override
    public void inicializar(String textoInicial) {
        setTitle(textoInicial);
    }
    
    @Override
    public void ingresarJugador(Jugador j) {
        try{
            new Juego(j).setVisible(true);
        }  
        catch(ObligatorioException ex){
            error(ex.getMessage());
        }
    }

    @Override
    public void ingresarAdministrador(Administrador a) {
        new Partidas().setVisible(true);
    }

    @Override
    public void error(String textoError) {
        JOptionPane.showMessageDialog(this, textoError);
    }

    @Override
    public void cerrar() {
        dispose();
    }

    
    
}
